### ISSUE TITLE
Style guide / guidelines

### ISSUE THREAD

**Issue by cpitclaudel** [realgud/realgud#117]
I don't have particular issues with the current style (parentheses on separate lines), but I'm not sure how to enforce it on my commits; same for indentation (whereas enforcing the standard style is pretty easy, in particular thanks to `aggressive-indent-mode`). As a result, some of my commits have included some minor reformattings here and there.

Is that an issue? If so, I can make myself a `.dir-locals.el` to prevent further reformattings from happening.

**Comment by rocky** [comment]
It's not an issue, as long as *I* don't have to conform to the lots of parens on a line.

My problem with that is that I find myself doing extra motion and keystrokes on those lines when a new statement is added or removed in a sequence of statements.  And with the parens on a single line it helps me understand the end bracking better. 

Worse in my opinion is Python and its _lack_ of an end symbol. In the early days Guido insisted it was a virtue. Now at least he admits it was a mistake.

But In my opinion it was  a _stupid_ mistake and I'm not sure why Python 3 didn't add at least an optional end symbol, which could be added at any time. That's why I use these `pass` and `return` statements in my Python code. But sadly that irks die-hard Pythonistas.

**Comment by cpitclaudel** [comment]
Got it; sounds perfect. I'll feel free to do indentation fixes, and I'll set up my Emacs to not rewrap parentheses.

Thanks for the clarification!
