### ISSUE TITLE
Wrong number of arguments on realgud-byebug and realgud-pry

### ISSUE THREAD

**Issue by sandric** [realgud/realgud#136]
I can't make it work in my 25.1.50 emacs - I installed realgud from melpa, and byebug and pry modules too. As said in instruction - I load library and then in file buffer running realgud:byebug. The thing is as I get it can not parse nor file name nor parameters for it - at first try it opened me blank byebug prompt. 
If I enter file name it starts comint mode with byebug prompt in it, but in place where file with realgud should go I see such error (with some unreadable characters):
```
realgud:byebug-track-mode: Wrong number of arguments: #[(debugger-name) "Æ	\"Æ\"Æ
\"'Ç!Æ
\"Æ

\"ZÈÉ
!ÊQË
ÌP!Íp
%Î!?VÏ!VÐ!*`ÑÒ\"Ó+" [debugger-name realgud:variable-basename-hash base-variable-name realgud-pat-hash regexp-hash realgud-command-hash gethash realgud:debugger-name-transform " " capitalize ...] 6 ("/Users/sandric/.emacs.d/elpa/realgud-20160618.1028/realgud/common/track.elc" . 17966) (list (completing-read "Debugger name: " realgud-pat-hash))], 2
```
Am I doing smth wrong or its a bug? Thx.

**Comment by rocky** [comment]
Probably my fault in that the API has changed. Will look at when I get a chance.

**Comment by rocky** [comment]
Both pry and byebug have been updated so they shouldn't give that error message. 
(The funny characters are a weird artifact of emacs lisp where it is showing bytecode because like most people you are running byte-compiled code0.

However the difference between something working well and not erroring is a different matter. I spent more time on byebug because I think I understand how to use it better. However support here is kind of lacking. 

Pry is its own world. 

Both projects could use some love and someone shepherding development. 

Finally, it probably would be better to open issues in those projects rather than here as that way the project tracks commits  merges and github stuff likethat.

**Comment by sandric** [comment]
I tried applying latest commit in byebug with recompiling whole package directory and nothing changed for me (I applied changes manually because updating via melpa didn't have changes) - starting realbug:byebug still looks like not substituting right file name and params and the same error next. Is this is the commit I need to [apply](https://github.com/realgud/realgud-byebug/commit/5b29991241959e6efdc28d9a90b80a4eb3e94d08)?

P.S. I started issue here because I tried both pry and byebug and since I got similar result I had a clue that it probably smth in parent package.

**Comment by rocky** [comment]
Yes, that commit needs t be there. The right version is on MELPA now, so you can update from that.

If there's a still are problems the be very detailed someone can reproduce the problem put that in the issue tracker for the associated project. 

One problem I know about, but don't know how to fix has to do with the fact that when you set a breakpoint the output doesn't tell you where the breakpoint was set. I probably need handle that the same way that we do for other debuggers.
