### ISSUE TITLE
evil compatibility

### ISSUE THREAD

**Issue by FelipeLema** [realgud/realgud#139]
Hello

I just realized that realgud is incompatible with [evil](https://www.emacswiki.org/emacs/Evil). I thought that changing and/or using prefix keys (which defaults to `^X^A`) would work out, but no. Namely, to evaluate an expression I tried `e` in insert (writes the "e" character), normal and visual modes (moves to end of word) and also with default and custom prefix, but no go.

One thing though, using `(evil-emacs-state)` makes the single-key shortcuts work. This is my current workflow, but I would like to use the prefix shortcut.

Maybe I'm understanding the docs incorrectly. Couldn't find complete info on this matter either.

**Comment by rocky** [comment]
I'm not an evil user and don't know that much about it. But if you are willing to work on it, this will probably get fixed. 

In source-code buffers while debugging, the mode you are in is called `realgud-short-key-mode`. That uses a key-mode map called `realgud:shortkey-mode-map`.  (Both of these variables have docstrings, so you can get help on each of them inside emacs.)

As an experiment, try binding `^X^A` to `realgud:shortkey-mode-map`. I think this will cause `^X^Ae` to run `realgud:cmd-eval-dwim`. 

If that works, this is probably too drastic since I guess you won't be able to use non-short-keymode prefix keys that you might have had. 

Short of what is described above, I'm not sure what additional information/documentation you are soliciting or need. If there's something you learn that you think others may benefit from, please consider adding information to the wiki.

**Comment by FelipeLema** [comment]
Ok, two things:

- I didn't know I could(/it was the emacs way to) assign a prefix to a map (using `(local-set-key …)`
- Evil has a way to deal with maps by customizing  `evil-overriding-maps` and `evil-intercept-maps`

I will update the wiki with this info by tomorrow and then close this issue. Thanks for the info

**Comment by rocky** [comment]
Thanks, and thanks for the info.

**Comment by FelipeLema** [comment]
Oh, btw: I was using `realgud-short-key-mode-hook` as a hook for source files being opened. Since I'd like to de-activate short-key mode (by customizing `realgud-short-key-on-tracing?`) what other hook can I use for "realgud:open-src-file-kind-of-function"?

**Comment by rocky** [comment]
Why not write your own hook that calls `realgud-short-key-mode-hook` under whatever conditions you find useful? 

Again, I am not following what you are asking.

**Comment by FelipeLema** [comment]
Nvm. Just edited the wiki with [the inf](https://github.com/realgud/realgud/wiki/How-to-Use#short-key-mode)o. Thx again

**Comment by rocky** [comment]
Thanks for the wiki contribution!
