### ISSUE TITLE
Open source files like cgdb.

### ISSUE THREAD

**Issue by amosbird** [realgud/realgud#148]
How can I search a source file and open in other buffer in order to add breakpoints like one does in `cgdb`?

**Comment by rocky** [comment]
I looked at cgdb, a curses based implementation of gdb.  I don't know how it gets a list of files that it reports. I know a lot of them for the library files were simply files that match the basename part of the name which I suppose is reasonable given that this is all that is recorded in the binary.

The closest thing to this in realgud is running a gdb `info files`.  To associate a source file that is not already associated with  a debugging session,  edit the source file and run `M-x short-key-mode`. It will then ask you the name of the buffer where the debugger is running.

I the long term, I guess we should add some sort of feature that runs the equivalent of "info files" and parses the output for the names of files so that when  a line with a file name is clicked it is brought up in another window. 

If you feel strongly enough about it, perhaps you can implement. It would be similar in code to the way the backtrace buffer is created.
