### ISSUE TITLE
undodb-gdb not supported

### ISSUE THREAD

**Issue by FelipeLema** [realgud/realgud#172]
IIRC undodb-gdb has more line commands (`undodb-get-n`,`undodb-goto-n`...) and a different prompt (`(undodb-gdb)`).

If you can point me out on what needs to be changed, I can do it myself. I tried but I didn't understand the hash getting/setting for a certain debugger. Can `realgud:gdb` be extended for undodb-gdb or does it need its own debugger folder?

Thanks

**Comment by rocky** [comment]
It looks like undo-gdb is really a different debugger although based on (if not an extension of) gdb, so  we shouldn't try to extend realgud's gdb to cover this but use another thing. We do the same thing for say Python extensions to the stock python debugger `pdb`, e.g. `ipdb`. 

Since the code is also proprietary which means not everyone will be able to use it, and since right now it isn't something that is mainstream popular (however it is cool), I think it really should be in a separate repository.  By the way this also helps keep down realgud's current bloat.

https://github.com/realgud/realgud/wiki/How-to-add-a-new-debugger has info on adding a new debugger inside the _existing_ realgud. I don't have instructions for what to do in this kind of situation where we want to add a new git repository, but it's not too bad. Take an existing project like `realgud-lldb` fork that changing it to `realgud-undo-gdb` and then start modifying the code starting with `gdb` from the reagud project.

**Comment by FelipeLema** [comment]
I ended up basing off `gdb`

**Comment by rocky** [comment]
That's most of the way there then. I've created a new repository [realgud-undo-gdb](https://github.com/realgud/realgud-undo-gdb/settings/collaboration) and you should have an invitation to become a collaborator (e.g. writer to that repository). 

As mentioned before, gdb is just too large right now and undo-gdb isn't freely available. So this is possibly the best way to handle for now.
