### ISSUE TITLE
fringe cursor is not recognizable in monokai theme

### ISSUE THREAD

**Issue by handrake0724** [realgud/realgud#176]
I found fringe cursor for pointing the current debugging line is not visible when a theme with dark theme like monokai is used.
The color could be changed if I edit black to red in realgud/common/fringe.el:59.

Is it possible to change the fringe color depending on background color?

**Comment by rocky** [comment]
> Is it possible to change the fringe color depending on background color?

If you looked at fringe.el around line 59 you see that yes, indeed it is possible to change the fringe color, since that's what it does there based on whether Emacs tells it if there is a dark or light background.

I checked, and the monokai theme does indeed register as dark. You can see this for yourself by running 
  
```
(frame-parameter nil 'background-mode)
```

The most likely thing that happened then is that this code was run in a frame that had a light background, because when there is a dark background the arrow is displayed in green. 

Alas, the changing of the arrow color is not that dynamic, it doesn't detect the backgrounds dynamically. I'm not sure how to fix this so it does. Perhaps someone else reading this will know. Or maybe you can google it. 

The other thing about this code is that the whole rotation of arrows and the magic number 3 is very hoaky. Again, I don't know how to do better, but perhaps someone will take pity and fix this code up. 

It very well may be that the very old overlay arrow mechanism can be replaced by something better.

**Comment by handrake0724** [comment]
Thanks a lot, rocky.
So, I have to stick to the current code until someone fix the issue.

**Comment by rocky** [comment]
Thinking about this more, I wonder if there's a way to have the monokai set foreground and background colors for `realgud-overlay-arrow1`,  `realgud-overlay-arrow2`,  and `realgud-overlay-arrow3` ?

**Comment by rocky** [comment]
Commit f884fe71bf0c1c8190279751c8b7d8c657770095 might address this now. If it does, close issue.

**Comment by rocky** [comment]
https://github.com/oneKelvinSmith/monokai-emacs/pull/76 definitely addresses.

**Comment by handrake0724** [comment]
Sorry for the late reply. I checked commit f884fe7 and found it works.
Thanks.
