### ISSUE TITLE
locals

### ISSUE THREAD

**Issue by FalseProtagonist** [realgud/realgud#191]
Is there a way to have a window showing locals?

If not are there any pointers on how I might implement it for python usine trepan or ipdb?

Thanks!

**Comment by rocky** [comment]
Here is an approach. Fork code. Do the same kinds of steps that was done in creating a backtrace buffer: 

1. Look at `realgud/common/cmds.el` and add a realgud command for getting locals. 
For example:

```
(defun realgud:cmd-info-locals ()
  "Run a command to show local variables"
  (interactive "")
   (realgud:cmd-run-command nil "info-locals")))
```
2. copy and modify `realgud/common/buffer/backtrace.el` to `locals.el` (or whatever you want to call it) in buffer directory. This directory holds different kinds of buffers and this would be a new one.

3. In `backtrace.el` you should find a function `backtrace-init`. That function and all of the backtrace- functions that need correspondence would get renamed to local.  That function runs `(realgud:cmd-backtrace 0)`  which issues the appropriate backtrace command to the underlying debugger.  It knoww how to run a backtrace command from a hash entry set up in say trepan2/init.el or trepan3k.int.el etc. 

Note that he actual `(realgud:cmd-backtrace 0)` is wrapped inside something that is diverting output to the new locals buffer you are creating. The code that diverts output and sends the command inside I think is flaky. If you could improve that somehow that would be most appreciated. 

For trepan2 you could add something like 
```
(setf (gethash "info-locals" realgud:trepan2-command-hash) "locals")
``` 
in its `trepan2/init.el` file. 

4. Another file you'll want to copy and modify is `common/buffer/backtrace-mode.el`. This sets up the mode of the backtrace buffer. So this might be `common/buffer/locals-mode.el` instead and you'd adjust the commands to do things that make sense in a buffer containing listing of locals variables. Personally, I've found making this some sort of Org mode buffer may be helpful. 

5. The last thing that you'd do is hook this into something that might get updated every time the debugger stops at a new location. That is located in `realgud/track.el`

But I'd suggest forgetting the last step for now. In fact you could forget about the generality creating a new "locals" realgud command and just hard-code a string for some debugger. And then when things work out as you expect then go in and generalize. 

In fact, if this suits you, and want it in realgud a pass has to be made to add all the other debuggers that have a command to query local variables. But I'll handle that.

Hope this helps. If you have questions, just ask.

**Comment by jodonnell** [comment]
i am thinking about implementing this as well as a watch expression window.

If someone else wants to add this I have something like this in a byebug debugger I was writing a while back that with Rocky's above description maybe helpful

https://github.com/jodonnell/emacs-ruby-debug/search?utf8=%E2%9C%93&q=ruby-debug--print-and-reset-vars&type=

**Comment by rocky** [comment]
@jodonnell Thanks considering to undertake. With all the recent and great work you and others have done on realguid, I am thinking of putting what is there after the eval work, and putting it into elpa, which is like melpa but just doesn't change as often.

**Comment by jodonnell** [comment]
Great, although maybe wait a week or two  to make sure I didn't break anything ;)

**Comment by rocky** [comment]
Yeah, I make a lot of mistakes. As you can see in the proposed changes to the eval code. So yes, we'll wait a week.

**Comment by JohnLunzer** [comment]
This would be an amazing addition if successful. 

I come from using pudb, which implements this as well as a window containing a list of stack frames. For anyone looking to getting this working with python the pudb code may be a good place to look for how they grab a list of the local variables. 

There are also plenty of posts on SO as well about getting local variables and their values, though I imagine if you're trying to do this for an arbitrary stack frame you'd have to be more clever than what most of the SO posts prescribe.

**Comment by jodonnell** [comment]
Hi John, I think it would have to depend on each debugger, for example byebug has a command called locals that will spit out all local variables and their values.

**Comment by JohnLunzer** [comment]
Indeed, the "standard" debuggers in python, pdb and ipdb, I believe do not have such straight forward methods for listing all local variables in the current stack frame. Which is why I tried to provide some additional context in the case of doing this with python.

**Comment by jodonnell** [comment]
Okay cool, I will check out pudb!

**Comment by rocky** [comment]
Well, the trepan debuggers trepan2 and trepan2 also can print out both locals and globals via
[info locals](http://python2-trepan.readthedocs.io/en/latest/commands/info/locals.html) and globals via [info globals](http://python3-trepan.readthedocs.io/en/latest/commands/info/globals.html).

**Comment by JohnLunzer** [comment]
In Python's case, in an effort to minimize reliance on dependencies, it makes the most sense to utilize the standard library. I believe both trepan and pudb take this same approach, with pygments being an optional dependency but ultimately relying on the standard library.

trepan would probably be another good study for how to grab the current stack frame's locals, and comparing it to how pudb does it should provide good insight into how to implement it on it's own.

**Comment by 813gan** [comment]
I have created [POC](https://gist.github.com/813gan/c29b9f08b2bb1bc448be8e42f7139f54) for pdb.  
It requires custom function available in pdb as this debugger does not define serious interface to talk with front-ends like gdb's `-i=mi`.  
It have obvious limitation; locals are not update automatically when debugger hits breakpoint.
@rocky do you have idea how to implement it? Maybe breakpoint hooking should be implemented?

**Comment by rocky** [comment]
One place to hook into might be [`realgud-track-loc-action`](https://github.com/realgud/realgud/blob/master/realgud/common/track.el#L365-L368).

**Comment by 813gan** [comment]
@rocky I pushed initial commit to [my fork](https://github.com/813gan/realgud/tree/locals-window)
Could you review it?

I personally see following limitations:
* locals have no formatting and at the beginning of buffer there is debugger command.
* there is no easy way for filtering variables
* No way for displaying globals && in python globals contain lot of multiline mess
* in contrast to breakpoint buffer user have to manually switch to new buffer.
Do you have idea how to solve it?

Also, i dont understand logic behind `realgud:window-*-undisturb-*` functions. Should i add one for locals?
Autorefresh is not ready yet, i have problems with removing hook, so buffer will re-create once used.

**Comment by rocky** [comment]
@813gan Ack. I'll take a look when I have a chance. Thanks in advance for undertaking.

**Comment by rocky** [comment]
@813gan - I cloned the repo and tried it. Alas, I could only get it to minimally work with some effort. Suggestions are below, but first the problems I encountered. And error I encountered a number of times was:

```
 Wrong type argument: realgud-loc-hist, #<mutex *pdb gcd.py shell*>
```

Tracking this down further this comes from `realgud-get-srcbuf` and sometimes `realgud-get-srcbuf-from-cmdbuf`.

I don't know more than that. 

The second error I found was: 

```
"Timeout on running debugger command"
```

This  is because you need to run  `info-locals` right after [`(setq realgud-track-divert-string nil)`](https://github.com/813gan/realgud/blob/locals-window/realgud/common/buffer/locals.el#L7). Compare with https://github.com/realgud/realgud/blob/master/realgud/common/buffer/backtrace.el#L123

And in order to do this you would need to *write* such an `info-locals` command `cmd.el` as was done for [`realgud:cmd-info-breakpoints`](https://github.com/realgud/realgud/blob/master/realgud/common/cmds.el#L359). 

Ok now to suggest some things to address your concerns. The thing that I notce and you have noticed with adding this is that there can be arbitrarily large output, so the timed wait which was akward to begin with gets even more akward. 

A better interface would be to first get just the _names_ of the varaibles (i.e. the keys of `locals()` and show that in an org buffer. When the user expands the variable name, then the value can be queried. I think programmers will find this not only more what they want (some particular variables expanded while others not, but listed) but cuts down on the unnecessary query and voluminous output back from the debugger. 

Lastly, to have the values format nicer, you can use pdb's (or better trepan3k's and trepan2's) `pp` command.

**Comment by 813gan** [comment]
@rocky thanks for your review. 

I remember that i had some problems with this "`#<mutex *pdb gcd.py shell*>`" but i cannot reproduce it now. Could you send me some details about your environment?

Thanks for your tips around timeout, i will apply changes soon.

Folding of variable values is absolutely must-have but i'm not sure if reusing Org is good idea as we will get newline between name and value, so it will consume more space.
Apart from that probably many people have extreme hacks in `org-mode-hook` - i bet it would cause some problems.

Apart form that I have some concerns around communication with debuggers. Can i assume that all debuggers will have ability to query all variable names && ability to get single variable's value && all debuggers will serialize data in sane format?

**Comment by rocky** [comment]
> Could you send me some details about your environment?

```M-x emacs version
GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.11) of 2019-09-23, modified by Debian
```

I'm more interested fixing the known flaws before doing work to track down the more nebulous problems. 

> Folding of variable values is absolutely must-have but i'm not sure if reusing Org is good idea as we will get newline between name and value, so it will consume more space.
> Apart from that probably many people have extreme hacks in org-mode-hook - i bet it would cause some problems.

I don't care *that* much as long as that something like that kind of interface works where you can easily elide and expand information. 

> Apart form that I have some concerns around communication with debuggers. Can i assume that all debuggers will have ability to query all variable names && ability to get single variable's value && all debuggers will serialize data in sane format?

That has always been something that we've had to work around. Of course different debuggers support different things. That's another reason why  `info-locals` has to be implemented as a *command* as I indicated earlier. 

If a debugger can't support everything that is needed to support `info-locals` then it is marked `**unsupported**`. See how [`frame` and `shell`](https://github.com/realgud/realgud/blob/master/realgud/debugger/pdb/init.el#L163-L164) are marked in pdb that way for example.

**Comment by 813gan** [comment]
@rocky I pushed suggested changes related to timeout issue. 
(the problem was that debugger was answering faster than emacs were setting variable with output to null, right?)

I need to do some research and think more about folding. I bet i will send some update next weekend.

I'm a bit concerned about this "mutex" thing. What versions of emacs-loc-changes are you using?

**Comment by rocky** [comment]
> (the problem was that debugger was answering faster than emacs were setting variable with output to null, right?)

I think that was occurring, but with a timeout it can also happen the other way around with lots of ouput and I think I saw that too. 

> What versions of emacs-loc-changes are you using?

20160801.1708

**Comment by 813gan** [comment]
@rocky  I propose following solution:
Instead storing all available data in buffer and setting text properties on unwanted values (and inserting new data in *correct* place when user expand value)
store variable names/values/other data in buffer-local data structure and overwrite buffer once something changes (debugger hits next breakpoint/user requests to show new variable etc).

Additionally it would be nice if frontend would remember expanded values, so it will be not necessary to hit TAB every time debugger goes to another function.
It means that data structure mentioned above would be not only buffer-local but also frame-specific which means that 
it would be necessary to somehow identify frames (and eventually fallback to dumb variable-name-based setting when it's only way)

If it's acceptable i will start working on it.

**Comment by rocky** [comment]
@813gan This sounds fine. Ambitious, but it doesn't sound like rocket science, just SMOP (small matter of programming). 

But in the end, if successfull, it would lead the way towards other kinds of frames for backtraces breakpoints, global variables, and so on.

**Comment by 813gan** [comment]
@rocky I [pushed](https://github.com/813gan/realgud/tree/locals-window-v2) more or less usable version of re-implemented locales.
Could you take a look?

Does "mutex" issue still occurs?

Problems that i spotted:
- It does not handle multi-line variables.
- When run "continue" and then quickly request variable value some garbage appears in output

**Comment by rocky** [comment]
Took a look and writhout ESP or debugging the code I can't get it to work. 

Maybe you could write a document that describes what it is and how you used. Maybe some screenshorts with examples. 

Here is what I tried. 

I cloned the repo and byte compiled everything using the comment in `realgud.el`
```
(compile (format "EMACSLOADPATH=:%s:%s:%s ./autogen.sh" (file-name-directory (locate-library "test-simple.elc")) (file-name-directory (locate-library "load-relative.elc")) (file-name-directory (locate-library "loc-changes.elc"))))
```

I did a `M-x load-file realgud.elc`. 

Then `M-x realgud:pdb`: 

```
Run realgud:pdb like this:
python -m pdb test/gcd.py 3 5
```

I get into the debugger and in the source window I type `L` and get:

```
Debugger entered--Lisp error: (wrong-type-argument realgud-loc-hist #<mutex *pdb gcd.py shell*>)
    16 signal(wrong-type-argument (realgud-loc-hist #<mutex *pdb gcd.py shell*>))
    16 realgud-loc-hist-item(#<mutex *pdb gcd.py shell*>)
    52 realgud-get-srcbuf-from-cmdbuf(#<buffer *pdb gcd.py shell*> nil)
    42 realgud-get-srcbuf(#<buffer *pdb gcd.py shell*>)
     9 realgud-expand-format("print( '\\n'.join(( '\\t'.join((var_name, repr(value..." nil)
     4 realgud-command("print( '\\n'.join(( '\\t'.join((var_name, repr(value..." nil nil nil nil)
   118 realgud:cmd-run-command(nil "info-locals")
     4 realgud:cmd-info-locals()
    29 realgud-locals-init()
    21 realgud:window-locals()
   102 funcall-interactively(realgud:window-locals)
   102 call-interactively(realgud:window-locals nil nil)
   102 command-execute(realgud:window-locals)
```

I am using this new branch that reports [bytecode-offsets in bytecode files](http://git.savannah.gnu.org/cgit/emacs.git/log/?h=feature/soc-bytecode-in-traceback-reduced). So for example if you disassemble `realgud-loc-hist-item`  you get: 

```
byte code for realgud-loc-hist-item:
  doc:  Get the current item of LOC-HIST at the position previously set
  args: (loc-hist)
0	constant  realgud-loc-hist-item-at
1	varref	  loc-hist
2	constant  type-of
3	varref	  loc-hist
4	call	  1
5	varref	  cl-struct-realgud-loc-hist-tags
6	memq	  
7	goto-if-not-nil 1
10	constant  signal
11	constant  wrong-type-argument
12	constant  realgud-loc-hist
13	varref	  loc-hist
14	list2	  
15	call	  2
16	discard	  
17:1	varref	  loc-hist
18	constant  1
19	aref	  
20	call	  2
21	return	  
```

with is the instruction after the `call 2` and corresponds to checking that `loc-hist` is valid for  a `realgud-loc-hist-item-at`
in 

```
  (realgud-loc-hist-item-at
   loc-hist ...)
```

I get the same thing without the bytecode offsets on Ubuntu's `GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.11) of 2019-09-23, modified by Debian`

**Comment by 813gan** [comment]
@rocky I'm out of ideas. I installed 26.3 from debian sid and followed your instructions and it still works.
Also, line `realgud-command("print( '\\n'.join(( '\\t'.join((var_name, repr(value..." nil nil nil nil)` suggest that you are working on old code. I created new branch: https://github.com/813gan/realgud/tree/locals-window-v2
Maybe this problem magically disappears there...

At my side i'm installing it this way:
I'm installing dependencies from melpa;
I execute script
```bash
set -x
cd /srv/git/realgud/ && \
git clean -fdx && \
export EMACSLOADPATH=:/home/dev/.emacs.d/elpa/test-simple-20170527.1532/:/home/dev/.emacs.d/elpa/load-relative-20190601.1221/:/home/dev/.emacs.d/elpa/loc-changes-20160801.1708/:/srv/git/realgud/ && \
./autogen.sh && \
./configure --prefix=$HOME/reg-test --with-lispdir=$HOME/reg-test && \
rm -rf ~/reg-test/ && make && make install
set +x
```
and running `(add-to-list 'load-path "/home/dev/reg-test/")` inside emacs.

**Comment by rocky** [comment]
> Also, line realgud-command("print( '\\n'.join(( '\\t'.join((var_name, repr(value..." nil nil nil nil) suggest that you are working on old code. 

Yes, it does. How, I am I still don't know. But by setting up a totally clean virtual environment I've been able to get this to work!

It has a number of problems that I think you are aware of. The most obvious (for me) is how to use. For some mysterious reason (probably not due to you) the Debugger menu in the command is now missing for me. 

So you have to know to type "L" in the source window to  invoke `(realgud:window-locals)` and after that happens to look for a `*locals pdb ...` buffer and switch to that. 

And then know that every time you step you need to update the locals window.  If making the locals window visible automatically is a problem, then just running `(message "Updated buffer *locals pdb ..)` or something similar would give people a clue.

Another problem as I think you mention is the handling of dictionaries. It feels like the same kind of thing for showing keys and values. So when you expand a dictionary you see the the first n keys; expand a key and you see the value if it is a scalar, but if another dictionary we iterate here. 

I wonder if there is a package that handles this kind of outlining. Somehow I feel that org mode or outline mode should have some way to allow it to be used as a minor mode in such way.   A suggestion is to ask on [StackOverflow for Emacs](https://emacs.stackexchange.com/).

With all of that out of the way, I do find this cool! I thank you for working on it. 

Since this is pretty well isolated, I am okay with putting in a PR as is and then iterating on it as you have time and desire. Up to you.

**Comment by 813gan** [comment]
>Debugger menu in the command is now missing

What do you mean?

>So you have to know to type "L" in the source window to invoke (realgud:window-locals) and after that happens to look for a *locals pdb ... buffer and switch to that.

Yes... i'm aware of it and i will inspect it now.

>kind elision for showing keys and values should be done.

Yes. data visualization tools are obvious next step. I will start working on it after fixing current issues.
I'm afraid that this feature will introduce far more debugger-specific code...

>I do find this cool!
>putting in a PR

Thanks! I'm really happy to hear it  : )
I bet i will open PR soon

**Comment by rocky** [comment]
> What do you mean?

![realgud-trepan3k](https://user-images.githubusercontent.com/8851/88466902-12473580-ce9f-11ea-98e8-e836e88ec2a6.png)

The word "Debugger" and the menu associated with that are gone. (I recently made a change in that area though, so that is the most likely reason). 


> I'm afraid that this feature will introduce far more debugger-specific code...

As I hoped to convey before, there are already mechanisms for mapping the ways you so something in a particular debugger with some more general concept. Specifically these are general concepts: 

* Querying the names of all local variables 
* Getting the type of a variable 
* Getting the value of a variable

So I don't see a problem. 

It is true that this feature should be added to _gdb_,  the trepan debuggers, the POSIX debuggers and so on. However that can be done at any time. After the first one is done (and in my opinion _pdb_ was a poor choice here since other debuggers handle this in a less clunky fashion), I am sure anyone interested in adding this kind of support would be able to do so.

**Comment by 813gan** [comment]
I'm working lot with python and shells. I can take care about related debuggers.
