### ISSUE TITLE
Taking some learnings from realgud to gud

### ISSUE THREAD

**Issue by jojojames** [realgud/realgud#206]
Hi, I've been looking into potentially improving GUD and/or using realgud to create new debuggers.

I raised a topic here: https://lists.gnu.org/archive/html/bug-gnu-emacs/2018-01/msg00617.html

Namely, realgud has some features that would be nice to have in gud (display of breakpoints for one).

I'm curious what the copyright status of realgud is before I take a look at its source code more heavily.

Thanks for the package! And would love your input in the same thread.

**Comment by rocky** [comment]
Improving GUD is a bad idea for the reasons mentioned in https://github.com/realgud/realgud/blob/master/realgud.el#L36-L47

Licensing is given in https://github.com/realgud/realgud/blob/master/COPYING

I am sorry to hear the EIi is just as lazy or thoughtless as you in trying to get answers as you seem to be. 

Please, before asking a question, make an effort to find out the answer.

**Comment by jojojames** [comment]
You seem to be having a bad day, I hope it'll get better for you.

Thanks anyway.

**Comment by rocky** [comment]
Well I let myself get distracted by your thoughtlessness. You have can have a direct impact on making things better. Thanks. 

Hey, tell you what. Do something really creative in realgud - that would really blow me away!

**Comment by rocky** [comment]
I have some free time and looked at the Emacs thread in more detail to follow links.

I don't agree with Eli's assessment or perhaps he misunderstood you and was answering something different. But I have found that the Emacs mailing list is probably not the right place to discuss this. At least not initially. I've just created a google group for realgud general discussions and have invited you to join. 

Eli asked you to be specific about what exactly you want to do, I don't think you have done that. 

It's okay to give generalities, but do that along with having some concrete examples, like the names of the debugging systems you want to hook into and the specific features you want to add. 

I took a look at https://code.visualstudio.com/docs/extensionAPI/api-debugging and that looks interesting. Sure, it would be interesting to write a front-end to that in Emacs rather than use the Microsoft supplied and probably proprietary front-end.
