### ISSUE TITLE
source code buffer is not shown when launching realgud:gdb

### ISSUE THREAD

**Issue by handrake0724** [realgud/realgud#207]
Hi,

I am not sure if it is about configuration problem.
I want source code buffer is shown when running realgud:gdb.
Currently, when I run realgud:gdb, only gdb shell is shown.
To show source buffer, I have to 
1) br main
2) run
 then, source buffer is shown and arrow cursor stops at main function.

Is it possible this behavior as I want?

Thanks in advance.

**Comment by rocky** [comment]
It would be helpful to have more information about what exactly you ran and what messages were shown back. In general usually in order to fix a problem one has to be able to reproduce it. 

Here is what I did: 

```
M-x realgud:gdb
Run gdb (like this): gdb test

Current directory: /home/rocky/c/
Command: gdb /home/rocky/c/ctest
set annotate 1
GNU gdb (Ubuntu 8.0.1-0ubuntu1) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/rocky/c/ctest...done.
(gdb) (gdb) break main
Breakpoint 1 at 0x40159c: file ctest.c, line 80.
(gdb) run
Starting program: /home/rocky/c/ctest 

Breakpoint 1, main (argc=1, argv=0x7fffffffe288) at ctest.c:80
/home/rocky/c/ctest.c:80:1988:beg:0x40159c
(gdb) 
```

One important thing you see in the output above is that "set annotate 1" is run in starting gdb. This is important as it produces that longish location message at the bottom: `home/rocky/c/ctest.c:80:1988:beg:0x40159c`

So the first thing to check is to see if that command is getting run and if you see these detailed location before the `(gdb)` prompt. 

But I imagine that even if `set annotate 1` wasn't run you should have seen the source because it also appears in the "Breakpoint 1".  So also try "frame 0" gives realgud another opportunity to see the location in output. 

Also look run `M-x realgud:cmdbuf-info-describe` it will list all of the locations realgud has seen. So with that we can separate the problem into realgud not having seen a location, versus not acting upon it properly.

**Comment by articuluxe** [comment]
I think he means that the source buffer is not shown when first executing realgud:gdb, only when the debugger is started. OP, I run ‘start’ instead for the same purpose. 

OP, while I sympathize with your desire, what source buffer would you suggest showing before the program had started, and how would realgud know which one to show by default?

**Comment by rocky** [comment]
@articuluxe many thanks for the information.  I didn't know there gdb had a start command. 

I'd be grateful if someone would update https://github.com/realgud/realgud/wiki/gdb-notes to make note of this possibly confusing behavior in https://github.com/realgud/realgud/wiki/gdb-notes

**Comment by handrake0724** [comment]
@rocky I am sorry I should have explained more cleary.
@articuluxe Thanks for filling the gap I missed and explaining the situation clearly. So, if the current behavior of realgud:gdb is intended, I am happy with start command at the moment because I normally start debugging with the source code with main function.

**Comment by rocky** [comment]
I have added @articuluxe 's info to https://github.com/realgud/realgud/wiki/gdb-notes

@handrake0724 please look over those notes for other tips or things that might be confusing. Feel free to add or amend if this is not clear.

**Comment by handrake0724** [comment]
@rocky Thanks for the wiki. I will take a look.
