### ISSUE TITLE
Source window out of sync with ipdb window

### ISSUE THREAD

**Issue by rbarzic** [realgud/realgud#229]
Hi,

I've installed realgud and tried it with ipdb and get this strange behaviour where the source code position indicated by ipdb is not updated in the source window (basically the green cursor in the source window is "late" compared to the current source line seen by pdb)

![image](https://user-images.githubusercontent.com/811506/49004657-04d72680-f165-11e8-9e5e-38532bf5426a.png)

I have the following message at the startup of ipdb :+1: 
WARNING: your terminal doesn't support cursor position requests (CPR).

I don't have the problem when running with pdb 

I've using realgud-20180925.10 from elpa on emacs 26.1

**Comment by rocky** [comment]
See if commit b8b587b fixes this. 

It looks like a new ANSI control sequence was added before the prompt (`> ...`) and that messed (messes?) up the location tracking.

**Comment by rocky** [comment]
One other thing - if the synchonization occasionally gets off, you can sometimes for a resync by issuing `up 0` in (i)pdb.

**Comment by rbarzic** [comment]
Thanks for the tip - Unfortunatly, I'm struggling a bit  to install the realgud stuff from git when not having sudo access and a local installation of emacs under /opt and be sure that the right version is used by emacs. I think I've install the latest version properly but the bug seems to be still here. Is there a way to get the version of realgud from emacs ?

**Comment by rocky** [comment]
This version of [realgud is already on melpa](https://melpa.org/#/realgud). 

To see whether you are getting the new code, you should not be seeing ASCII escape characters like
`[J>`  before where it shows where you are stopped or `[6C` afterward listing the source code.

Also, you need to make sure you are running in new comint shell, so that the changed functions are picked up.: shell hook, which is where the change is, store a copy of the function and don't automatcally get updated when the function changes. 

The simplest thing is to do here then is run  new emacs where you load everything from scratch.

Since Emacs is dynamic, all you need to do is `load-file` any of the files that have changed, before running realgud for the first time. To get a list of files that have changed, look at the commit. 

And lastly, I note that for a guy that seems to request this much assistance [you are relucant to star _any_ project](https://github.com/rbarzic?tab=stars)

**Comment by rbarzic** [comment]
Yes I did - And I don't have any ASCII escape sequence on screen. Only the message "WARNING: your terminal doesn't support cursor position requests (CPR)" at the beginning of the session.

**Comment by rocky** [comment]
Ok. Well, if this doesn't do it, then I guess I would like to leave it here. Things work for me well enough with this. (Actually, I don't use ipdb at all.)  

As this is open source feel free to dig in and investiage and/or fix. Or we can wait until someone else is interested in this.

**Comment by rbarzic** [comment]
ok I understand - I'm not particularly familiar with emacs interaction with other processes so I may not be able to help much on this unfortunatly

**Comment by rocky** [comment]
No one is born understanding emacs interaction with other processes.

**Comment by rocky** [comment]
Issue moved to [realgud/realgud-ipdb #2](https://github.com/realgud/realgud-ipdb/issues/2) via [**ZenHub**](https://www.zenhub.com/)
