### ISSUE TITLE
How to add specific code for setting a break point (pyqt) ?

### ISSUE THREAD

**Issue by azzamsa** [realgud/realgud#237]
I was able to do debugging in 'normal' python code. But for pyqt code, I need some code to wrap `import pdb; set_trace()`. it's:

```python
def debug_trace():
  '''Set a tracepoint in the Python debugger that works with Qt'''
  from PyQt5.QtCore import pyqtRemoveInputHook

  from pdb import set_trace
  pyqtRemoveInputHook()
  set_trace()
```
Taken from [here](https://stackoverflow.com/a/1745965/6000005)

How to accomplish this in realgud ?

Thanks.

**Comment by dolorsitatem** [comment]
I've had better luck with `ipdb` instead of `pdb`.  That's a detail though.  I believe `realgud` will function the same for both. 

I run the debugger by calling `M-x ipdb` and appending `python -m` at the beginning of the command so that it reads `python -m ipdb /path/to/program.py`.  This displays two buffers, one with the ipdb console output and the other with a read only version of `program.py`.  

I can use the regular `ipdb` commands in the `ipdb` buffer.  In the `program.py` buffer, `realgud` key mappings are applied.  Current keybindings are listed if you hit `C-h m` in the `program.py` buffer.  The one you want is `realgud:cmd-break`.  For me, this is bound to `<f9>`.  

Altogether, there are two ways to set a breakpoint.  First, using the `ipdb` console, you could do `b 5` to set a breakpoint at line 5.  Second, you could put your point on line 5 in `program.py` and press `<f9>`.

**Comment by azzamsa** [comment]
Now I often use ipdb in terminal.
