### ISSUE TITLE
Location tracking with pdb++ (pdbpp)

### ISSUE THREAD

**Issue by TauPan** [realgud/realgud#245]
Hi!

I've filed https://github.com/antocuni/pdb/issues/208 against pdb++ and it turns out the easiest fix that occured to me was to put the following elisp into my `.emacs`:
```elisp
(setf (gethash "loc" realgud:pdb-pat-hash)
      (make-realgud-loc-pat
       :regexp "> \\(\\(?:[a-zA-Z]:\\)?[-a-zA-Z0-9_/.\\\\ ]+\\)(\\([0-9]+\\))"
       :file-group 1
       :line-group 2))
```

(See https://github.com/antocuni/pdb/issues/208#issuecomment-488098626 )

Wondering how you feel about relaxing the regexp to suit pdb++, as it appears compatible with plain pdb in all other aspects (I've done a bit of debugging with pdb++ and realgud and found no other issues so far).

**Comment by TauPan** [comment]
(There's some similarity with #229 but of course ipdb is something directly supported by realgud.)

**Comment by rocky** [comment]
The best thing to do is to create a repo for this specific pdb variant. And as of yesterday or so, it got even easier to do for pdb-variants. 

git clone the recently-created ipdb. 

```
$ git clone git@github.com:realgud/realgud-ipdb.git
```

Then change whatever you want. Where _ipdb_ deviates from _pdb_ and you want the _pdb_ behavior, just copy that from the main realgud repository. 

And add whatever changes you want to make. 

When that's done point me to the repository and I will clone it into the realgud space and make you and admnistrator.

**Comment by TauPan** [comment]
Realgud is designed to be a dropin replacement to pdb, so it would be more appropriate to start with the pdb sources, as the regexp is literally the only thing that needs to be different at the moment.

(Note that putting the `setf` into my emacs doesn't really help, as I discovered today, as realgud-pdb will overwrite it.)

So what I could do is create a repo for the original pdb backend sources, clone that and create a 'pdb++'  backend for realgud by dropping the '^' from the regexp.

What problems do you see with dropping the '^' from the start of the regex?

**Comment by rocky** [comment]
> So what I could do is create a repo for the original pdb backend sources, clone that and create a 'pdb++' backend for realgud by dropping the '^' from the regexp.

> What problems do you see with dropping the '^' from the start of the regex?

From http://regex.info/blog/2006-09-15/247

> Some people, when confronted with a problem, think 
> “I know, I'll use regular expressions.”   Now they have two problems.

Well, technically I've gone down that road in _realgud_, but I am conscious to limit regexps when they refer to different things as they do here. 

Conceptually you want the _pdb_ front-end to work with _pdb++_ as well. This is not clean. _pdb++_ may make more changes and that would mean more changes to _realgud_. 

Since I am not seeing that you have contributed at all to _realgud_ (actually, you haven't even upvoted the project either), from my standpoint you are saying: hey couldn't you just add one more burden to support for a debugger that I use. You've already used the argument: you support _x_ so you it is not that much more work to add _y_. 

I am happy to assist _others_ who want to extend _realgud_ to work with their favorite debugger that I don't care about. However I don't have the time or desire to work on the realgud support for debuggers that I don't use. 

Instead, the direction I am moving in is to move individual debugger support _out_ of _realgud_ into individual projects. More smaller projects is good. One big monolithic project is bad.

So _ipdb_ will be moving out. Maybe _pdb_ will follow. That way, individuals can maintain and support debuggers that they care about, and in a smaller more isolated way.  And _realgud_ can better focus on the common parts, as it should. 

The main reason this hasn't happened previously is because of a bootstrap problem. It took work to get the separation down. In the meantime we wanted folks to be able to use _realgud_ for the most popular debugger, of which _pdb++_ is not in that list.

So let me turn it around: what problem do you see in adding a pdb++ repository that has the change you want?

**Comment by TauPan** [comment]
> > So what I could do is create a repo for the original pdb backend sources, clone that and create a 'pdb++' backend for realgud by dropping the '^' from the regexp.


> > What problems do you see with dropping the '^' from the start of the regex?
[...]

You've explained that quite well, I think.


> So let me turn it around: what problem do you see in adding a pdb++ repository that has the change you want?

Only that it would contain loads of duplicated code, but that is not really an issue at all for me right now.

**Comment by rocky** [comment]
> Only that it would contain loads of duplicated code

Yes, that is a problem I have grappled with. In realgud what I have done to try to ameliorate this is create a module for each language. So common definitions involving the CPython interpreter such as the kinds exception backtraces it gives. I've generalized that a little bit to things involving say flake8 messages and pytest messages. And even, probably wrongly, trepan debugger common kinds of things. 

If there turns out to desirable a separate module for pdb-derived debugger can be added. However, let's get to the point where it is more of a real problem rather than a slight annoyance.

**Comment by TauPan** [comment]
> If there turns out to desirable to create a separate module for pdb-derived debuggers, that can be done. However, let's get to the point where it is more of a real problem rather than a slight annoyance.

I've decided I can live with a workaround for now and updated the initial issue description to describe my personal workarounds. Should pdb++ deviate more from pdb one day (which would be against their mission statement, but such things are not unheard of in the software world) and I still wanted to use it with realgud, I'll consider creating a module to support it.

**Comment by TauPan** [comment]
Hmpf, unfortunately my workaround doesn't work. I've updated the regexp like this:

```elisp
(setf
                (gethash "loc" realgud:pdb-pat-hash)
                (make-realgud-loc-pat
                 :regexp "^\\[[0-9]+\\] > \\(\\(?:[a-zA-Z]:\\)?[-a-zA-Z0-9_/.\\\\ ]+\\)(\\([0-9]+\\))\\(\\(?:[a-zA-Z]:\\)?[a-zA-Z0-9_\\\\]+\\)()"
                 :file-group 1
                 :line-group 2
                 :function-group 3))
```

And in regexp-builder I can see that it matches every source line.

But

 - realgud:pdb doesn't track the first hit in a pdb break caused a test failure with `pytest --pdb`
 - realgud:pdb doesn't track every line this way.

No idea what's wrong here, so I'll switch back to plain pdb for now. Maybe somebody has an idea.

**Comment by rocky** [comment]
I am not following or interested in your personal workarounds except to the extent that they could be usable by others. And in that case I'd suggest you put them in the realgud wiki, which you could do at anytime. 

However, if you want my help, then do what I asked and start a separate project project for pdb++.

**Comment by rocky** [comment]
If there are others who are interested in pdb++ those people will see the repositry, see your problem and may be able to help. As things stand right now. I doubt even a pdb++ user is going to find this, and go through the effort to try your workaround based on what you've described here. to figure out what's wrong.

**Comment by rocky** [comment]
One other thing... have you tried trepan2 ?

**Comment by blueyed** [comment]
> * realgud:pdb doesn't track the first hit in a pdb break caused a test failure with `pytest --pdb`

Interesting.
Is this due to hidden frames maybe?

```
% pytest --pdbcls pdb:pdb.Pdb t-pytest.py
…
> /home/user/Vcs/pdbpp/t-pytest.py(10)test_1()
-> x = 3
(Pdb) q
```

```
% pytest --pdbcls pdb:Pdb t-pytest.py
…
[30] > /home/user/Vcs/pdbpp/t-pytest.py(10)test_1()
-> x = 3
   5 frames hidden (try 'help hidden_frames')
(Pdb++) q
```
