### ISSUE TITLE
Running `comint-clear-buffer()` inside realgud-track-mode causes strange behavior 

### ISSUE THREAD

**Issue by luluman** [realgud/realgud#264]
When ennable "realgud-track-mode" in a shell buffer and track GDB, I can not call "comint-clear-buffer". Realgud will complete out of control after I delete something in shell buffer. Here is an error message. 

> error in process filter: realgud:remove-ansi-schmutz-in-string: Args out of range: #<buffer sh-ufw>.

I don't know how to fix it. The only thing I can do is remind myself not to use "comint-clear-buffer" command when Readlgud is enabled. 

Also, I will be stuck in minibufer when my cursor in minibufer and the programming been tracked running into a breakpoint. I will get a snippet code in minibufer and never be able to close the minibufer any more.

I will be appreciated if someone can help me. Thanks.

**Comment by rocky** [comment]
Realgud keeps a list of marks in the command buffer, so clearing the buffer needs to be coordinated with the information that realgud has stored in the buffer. 

I'm not sure what the best solution here is. Not storing marks in the buffer isn't an option, since that is fundamental to how realgud works: it looks at text from the position you had been at to figure out what's gone on in the debugger. 

As you mention if you get out of realgud-track-mode, clear the buffer and then go back into realgud-track-mode you'll be okay (and lose all history of any debug session you had in that buffer).

realgud could hijack the use of comint-truncate-buffer which is the underlying function that does the damage, if there is no better way to do this. I don't know though.

**Comment by luluman** [comment]
Thanks for your explanation, it makes sense to me now. Realgud is great when debugging something which relies on many environment variables.

**Comment by rocky** [comment]
Since realgud does get sluggish when command buffers are thousands of line, I just added two command to delete portions of the buffer while keeping the realgud information in tact. 

See  https://github.com/realgud/realgud/tree/feature/comint-truncate-buffer

It might be nice to hijack comint-clear-buffer when track-mode is in effect and reset it when the mode is left. Feel free to add.

**Comment by rocky** [comment]
I added a sponsor button recently.
