### ISSUE TITLE
Add xdebug debugger

### ISSUE THREAD

**Issue by Sasanidas** [realgud/realgud#274]
Recently xdebug just release a [interactive debugger command line client](https://xdebug.org/docs/dbgpClient), and I was thinking if it is in a appropriated state to create a realgud plug-in for it.

I'm not an expert by all means in debuggers but if it is not too hard, I would like to implement a realgud-xdebug package

Thank you!

**Comment by rocky** [comment]
Please do - see https://github.com/realgud/realgud/wiki/How-to-add-a-new-debugger for instructions on how to get started. 

From brief lookover, probably the [jdb realgud project](https://github.com/realgud/realgud-jdb) would be a good place to start. 

When you have something lemme know!

**Comment by Sasanidas** [comment]
> Please do - see https://github.com/realgud/realgud/wiki/How-to-add-a-new-debugger for instructions on how to get started.
> 
> From brief lookover, probably the [jdb realgud project](https://github.com/realgud/realgud-jdb) would be a good place to start.
> 
> When you have something lemme know!

Sure, thank you for the tip! :+1:

**Comment by Sasanidas** [comment]
Hello again @rocky , sorry for the delay, I've been working on it these days, and for now the "basic" functionality works, like it creates the debug buffer and the basic commands (step in/out/over, restart quit) works, but I cannot make it to follow the execution file.

This can be because in the start, if no command is send, xdebug doesn't give you any information about the file that is currently in, and it doesn't accept the filename in the command line. 

I'm testing with a more or less complex PHP framework (Drupal) so it's not just a index.php, there is route and stuff before the buffer that the user may be in.
I'm having troubles setting the breakpoint and make it follow, if you can give me a hand/tip it would be very useful.
The repository is [here](https://gitlab.com/sasanidas/realgud-xdebug) (if gitlab is a problem, I can move it here).

Thank you very much.

**Comment by rocky** [comment]
I'd like to help but I don't have much time, and I have a hard time following in any great detail.

I don't generally use Drupal or PHP for that matter. Rather than work on a difficult problem why not first try a simple one?

One thing I see that looks too restrictive is rhe pattern used for [`realgud:xdebug-pat-hash`](https://gitlab.com/sasanidas/realgud-xdebug/-/blob/master/xdebug/init.el#L48) on line 48: 

```lisp
(setf (gethash "loc" realgud:xdebug-pat-hash)
      (make-realgud-loc-pat
       :regexp "Debugging file://\\(?:/\\|[[:alpha:]]\\|[[:punct:]]\\|[[:digit:]]\\)*[[:space:]]\\s(ID:[[:space:]][[:digit:]]*/\\(?:[[:alpha:]]\\|[[:punct:]]\\)*\\s)"
       :file-group 1
       :line-group 2))
```

When I compare with what I see at [Command Line Debug Client](https://xdebug.org/docs/dbgpClient) for the results of `step into`: 

```
(cmd) step_into
1 | step_into > break/ok
1 | file:///tmp/xdebug-test-2.php:14
```

I don't see the preifx `Debugging file` printed above, although a location is shown. So I'd drop the "Debugging " prefix and see if that helps.

But before I'd do this, I'd fix up  (and rename the file to be xdebug-specific not ipdb) the regular expression test case currently called  [`test-regexp-ipdb.el`](https://gitlab.com/sasanidas/realgud-xdebug/-/blob/master/test/test-regexp-ipdb.el). 

In particular, [Lines 37-45](https://gitlab.com/sasanidas/realgud-xdebug/-/blob/master/test/test-regexp-ipdb.el#L37-45):

```
(setq test-text
      "  File \"/usr/lib/python2.6/code.py\", line 281, in raw_input")
(note "traceback location matching")

(assert-t (numberp (loc-match test-text tb-pat)) "basic traceback location")

(assert-equal "/usr/lib/python2.6/code.py"
	      (match-string (realgud-loc-pat-file-group tb-pat)
			    test-text))

```

Adjust these strings to be the strings you find in the dbgpClient, and the in isolation you can check to make sure the regular expressions are correct. Trying to do this inside the real debugger is for me too combersome. 

I hope this helps.

Good luck!

**Comment by Sasanidas** [comment]
I think now the [realgud:xdebug-pat-hash](https://gitlab.com/sasanidas/realgud-xdebug/-/blob/master/xdebug/init.el#L71) works, and seems like some of the basic commands works, the backtrace still does something kind of weird, opening another window with no results, but it actually calls the command correctly.

I recorded a video so illustrate the problems:
**[video](https://vimeo.com/465191221)**

I tried to modify the test files but I don't know why it's giving me some error and doesn't run the test, it may be a problem with my config. 

Again, thanks for the help!

**Comment by rocky** [comment]
The video helps a lot.  From what I can tell the source-code isn't in realgud-short-key mode.  It looks like you are applying a menu break command against the command buffer. But the command buffer doesn't contain source code. 

In the command buffer you shouldn't use the menu break but just issue  a `breakpoint_set -t line -f file:///...` command and check that realgud tracks that the breakpoint gets set. 

Also when I see the debugger info, I  am not seeing mapping from a breakpoint command to the corresponding xdebug command like I do for `backtrace` or `info value`. Since there is nothing there and this command is not noted as being unimplemented, when you run break from the menu, realgud is issuing gdb's break command and not knowing what to supply for the filename and line number, since this is a command buffer. 

If you are not seeing the information appear in the backtrace buffer but instead it appears in the command line, then the mechanism for catching output from the command line is not working. This is done in `realgud_backtrace_init` and the signaling variable `divert-output` is done via `(realgud-cmdbuf-info-divert-output?= t)` in init.

**Comment by Sasanidas** [comment]
Ok, now the file loc works! It follows the file and can set the breakpoints
Here is a [video](https://vimeo.com/465886148) on how it works right now.

There is a couple of problem:
 - In order to delete/get/edit a break point, I need the breakpoint ID, so I have to implement some logic there.
 - The eval statement is broken, so I can only retrieve information about variables with `property_get`
 - The information about a variable, is given in a short of json format, so get the output of the command and render 
  it may be interesting

Here is an example of how the breakpoint set and delete works:

![Screenshot 2020-10-07 20:27:13](https://user-images.githubusercontent.com/26670956/95372750-49dd4f80-08dc-11eb-9d22-5d4319b6bd73.png)

Here is how the variable is show with the command line command:
![Screenshot 2020-10-07 20:36:20](https://user-images.githubusercontent.com/26670956/95373176-e3a4fc80-08dc-11eb-8f3f-58865dc42ea9.png)

And here is how it show the same variable, clicking with the mouse middle button:
![Screenshot 2020-10-07 20:36:59](https://user-images.githubusercontent.com/26670956/95373226-fcadad80-08dc-11eb-97a4-aec2ed5a9bfc.png)

It show the popup and in the minibuffer area, but just for a moment.

But is going forward, thanks for the help!
If the Realgud mantainers want to, I would like to help with the documentation and the presentation of the project in general, like a static web page for example.

Regards.

**Comment by rocky** [comment]
> In order to delete/get/edit a break point, I need the breakpoint ID, so I have to implement some logic there.

The "break-set" regexp is where you trap what breakpoint to use. Here is what you have:
```
;;  realgud-loc-pat that describes a "breakpoint set" line. For example:
;;     Breakpoint 1 at /usr/bin/xdebug:7
(setf (gethash "brkpt-set" realgud:xdebug-pat-hash)
      (make-realgud-loc-pat
       :regexp "breakpoint_set -t line -f file://+\\(/.+\\) -n \\([0-9]+\\)"
       :num 1
       :file-group 1
       :line-group 2))
```

The "num"  value (1) is the same value as `file-group` which is wrong. Actually, all of this looks wrong. It looks like you should be mathcing "Breakpoint set with ID xxxx" and associating that with the last breakpoint infomation you just entered. You'd have to go with the last breakpoint set since, It looks like the file and line are not reported back in the status, just the Breakpoint id.

As for help, the project needs help. Lots of it. So whatever you can offer is appreciated. 

Feel free to add this to https://github.com/realgud/realgud/wiki/Debuggers-Available when you think it is ready. 

Also I'd be grateful if you went over https://github.com/realgud/realgud/wiki/How-to-add-a-new-debugger to see that this matches what you just experienced. I'm sure since this is fresh in your mind, you'd know how to best improve it.

**Comment by Sasanidas** [comment]
ok, here is the [new video](https://vimeo.com/467096945), it shows that the set function seems to work fine, also it deletes the breakpoint.

The thing that doesn't work, is the visual debugger point, i suspect this can be cause because `brkpt-del`, right?
 I think don't fully understand the part that need to be parsed.

Everything else, seems to work fine :+1:

**Comment by Sasanidas** [comment]
Hello @rocky , the repo is out and I think this issue is already solve.
Thank for the amazing help, without it, I doubt I could complete this task in a reasonable time. :sunrise:

**Comment by rocky** [comment]
I am glad eerython worked out.
