### ISSUE TITLE
gdb target remote doesn't complete the connection

### ISSUE THREAD

**Issue by jkordani** [realgud/realgud#291]
gdb -v
GNU gdb (GDB) 10.1

  realgud            20201221.1435 installed

I start gdbserver then in gdb issue target remote blah
I have tried starting gdb with no args and also i=mi

**Comment by rocky** [comment]
I don't have a problem. One thing that you probably have to issue though is `set annotate 1`  in the local (non-gdbserver) session you are running so that position information is shown before a gdb prompt. 

Here is a screenshot

![gdbserver](https://user-images.githubusercontent.com/8851/112396190-1baacb00-8cd6-11eb-8d95-ebbe1d0940b9.png)

**Comment by jkordani** [comment]
![Screenshot from 2021-03-24 22-49-33](https://user-images.githubusercontent.com/1106403/112411518-6981fc00-8cf3-11eb-8912-f96efb4163ba.png)

**Comment by jkordani** [comment]
I can reproduce this with plain gdb mode.  I think gdbserver is messed up
