### ISSUE TITLE
Several issues with mixed up keybindings

### ISSUE THREAD

**Issue by cohomology** [realgud/realgud#65]
There are several issues with mixed up keybindings in realgud. I have a `(global-set-key [f5] 'realgud:cmd-step)` in my init.el. This is resetted to something horrible, although I set `realgud-populate-common-fn-keys-function` to `nil` in my init.el. 

This will be addressed partially in a forthcomming pull request. 

After my patch, this issue is not completely gone, however. `realgud:cmd-step` is still resetted to f11  sometimes, although I can't find where this is done. I will further investigate possibly.

Another question would be, why `realgud-populate-common-keys` is called nearly after _every_ action in realgud.
Best regards,
Kilian.

**Comment by rocky** [comment]
This is code that @expez initially added for a previous incarnation of this code. I believe the motivation was not to use keybinding inheritance of later emacses that weren't available in prior versions. 

The specific choice of what f5 is bound to I think was intended to match keybindings that are using in Microsoft debuggers on Windows. As a general principle, please be sensitive to the fact that what you may think is horrible may be ideal for someone else and vice versa. 

Personally, I don't care about or use _any_ of the function keys. But I _do_ worry that making things to suit your liking may have the opposite effect for someone else. We've seen this before in code you have that assumes you want a split horizontal window in certain circumstances. That's perfectly fine and I think even admirable for you to customize code to your liking. If you want to share your code with others of like mind even better! It is not okay though however to foist this code on others, unless I get feedback from others. 

@expez would you please comment on where you think things stand, this pull request in particular and shepherd things to what I hope will be something that is mutually acceptable? Thanks.

**Comment by expez** [comment]
I just packaged this up, to make installation easier, way back when.  I haven't written any of the code in the package itself.  You'll see this if you do `git blame` on the file in question.

As to the PR in question I think this is a good idea.  Keybindings for the function keys should be opt-in, as user's will often bind these themselves.  The issue with this PR is that a lot of users probably also prefer that we DO bind the function keys, like before, so the installation instructions should probably be updated to let user's know how to get the old behavior.

That all said, I don't use this package anymore (because I no longer write any ruby code) so I don't have much interest in being involved in this discussion going forward.

**Comment by cohomology** [comment]
This bug report is not about specific key settings. It is about changing the users keysettings, although  ```realgud-populate-common-fn-keys-function``` was ```nil```. I don't care about horrible (for me) keybindings, if I can change them. 

Although I would like if realgud would not mess with my keybindings by default.

**Comment by expez** [comment]
> They should only be setted when a major or minor mode is changed, right?

yes

**Comment by rocky** [comment]
Ok thanks will go with this change then.

Ok, we'll move in the direction you all agree on.

It sounds though like there is more work to be done in terms of documenting how to get the old behavior and setting only when a major or minor mode is changed, right? 

If this is correct, @cohomology would you please make the additional changes?

**Comment by cohomology** [comment]
Aggreed.
